parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     blogsymfony2
    database_user:     postgres
    database_password: postgres

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            ja
    secret:            ThisTokenIsNotSoSecretChangeIt
